# Generated by Django 5.0.7 on 2024-10-27 21:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entidade', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('data_abertura', models.DateField()),
                ('salario', models.BigIntegerField()),
                ('nivel', models.CharField(choices=[('FUNDAMENTAL', 'Fundamental'), ('MEDIO', 'Médio'), ('SUPERIOR', 'Superior')], max_length=20)),
                ('data_prova', models.DateField()),
                ('area', models.CharField(max_length=255)),
                ('iniciado', models.BooleanField(default=False)),
                ('finalizado', models.BooleanField(default=False)),
                ('inscrito', models.BooleanField(default=False)),
                ('field_13', models.BigIntegerField(blank=True, null=True)),
                ('banca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.banca')),
            ],
        ),
        migrations.CreateModel(
            name='ConcursoTopico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.concurso')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enunciado', models.TextField()),
                ('alternativa_1', models.TextField(blank=True, null=True)),
                ('correta_1', models.BooleanField(default=False)),
                ('alternativa_2', models.TextField(blank=True, null=True)),
                ('correta_2', models.BooleanField(default=False)),
                ('alternativa_3', models.TextField(blank=True, null=True)),
                ('correta_3', models.BooleanField(default=False)),
                ('alternativa_4', models.TextField(blank=True, null=True)),
                ('correta_4', models.BooleanField(default=False)),
                ('alternativa_5', models.TextField(blank=True, null=True)),
                ('correta_5', models.BooleanField(default=False)),
                ('banca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.banca')),
                ('concurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.concurso')),
            ],
        ),
        migrations.CreateModel(
            name='QuestaoRealizada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acerto', models.BooleanField()),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.questao')),
            ],
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('nivel', models.CharField(max_length=255)),
                ('concursos', models.ManyToManyField(through='api.ConcursoTopico', to='api.concurso')),
            ],
        ),
        migrations.CreateModel(
            name='QuestaoTopico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.questao')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.topico')),
            ],
        ),
        migrations.AddField(
            model_name='questao',
            name='topicos',
            field=models.ManyToManyField(through='api.QuestaoTopico', to='api.topico'),
        ),
        migrations.AddField(
            model_name='concursotopico',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.topico'),
        ),
        migrations.CreateModel(
            name='TopicoDisciplina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disciplina')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.topico')),
            ],
        ),
        migrations.AddField(
            model_name='topico',
            name='disciplinas',
            field=models.ManyToManyField(through='api.TopicoDisciplina', to='api.disciplina'),
        ),
        migrations.CreateModel(
            name='TopicoEstudado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_estudo', models.DateField()),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.topico')),
            ],
            options={
                'verbose_name_plural': 'Topicos Estudados',
            },
        ),
    ]
