# Generated by Django 5.0.7 on 2024-10-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concurso',
            name='field_13',
        ),
    ]
