# Generated by Django 5.0.7 on 2024-10-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_concurso_field_13'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicoestudado',
            name='topico',
        ),
        migrations.AddField(
            model_name='questao',
            name='acerto',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questao',
            name='data_realizada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topico',
            name='data_estudo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='QuestaoRealizada',
        ),
        migrations.DeleteModel(
            name='TopicoEstudado',
        ),
    ]
