# Generated by Django 5.0.7 on 2024-10-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_topicoestudado_topico_questao_acerto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topico',
            name='nivel',
        ),
        migrations.AlterField(
            model_name='concurso',
            name='nivel',
            field=models.CharField(choices=[('Fundamental', 'Fundamental'), ('Médio', 'Médio'), ('Superior', 'Superior')], max_length=20),
        ),
    ]
