# Generated by Django 5.0.7 on 2024-10-28 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_topico_nivel_alter_concurso_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topico',
            name='disciplinas',
        ),
        migrations.AddField(
            model_name='topico',
            name='disciplina',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.disciplina'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TopicoDisciplina',
        ),
    ]
