# Generated by Django 5.0.7 on 2024-10-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_topico_disciplinas_topico_disciplina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='alternativa_1',
            field=models.TextField(default='Alternativa 1'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_2',
            field=models.TextField(default='Alternativa 2'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='correta_1',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questao',
            name='correta_2',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questao',
            name='correta_3',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questao',
            name='correta_4',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questao',
            name='correta_5',
            field=models.BooleanField(),
        ),
    ]
