# Generated by Django 5.0.7 on 2024-10-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_questao_alternativa_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='alternativa_1',
            field=models.TextField(default='Verdadeiro'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_2',
            field=models.TextField(default='Falso'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='correta_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='questao',
            name='correta_2',
            field=models.BooleanField(default=False),
        ),
    ]
