# Generated by Django 5.0.7 on 2024-10-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_questao_alternativa_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='anulada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questao',
            name='correta_3',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='questao',
            name='correta_4',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='questao',
            name='correta_5',
            field=models.BooleanField(blank=True),
        ),
    ]
