# Generated by Django 5.0.7 on 2024-10-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_grupotopico_topico_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurso',
            name='edital',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='concurso',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
