# Generated by Django 5.0.7 on 2024-10-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_concurso_edital_alter_concurso_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurso',
            name='edital',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
