# Generated by Django 5.0.7 on 2024-11-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_concurso_edital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='acerto',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='correta_1',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='correta_2',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='correta_3',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='correta_4',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='correta_5',
        ),
        migrations.AddField(
            model_name='questao',
            name='correta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questao',
            name='resolucao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questao',
            name='resposta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_2',
            field=models.TextField(),
        ),
    ]
